'use strict';

 /**
 * event controller file * autogenerated by mongoose-scaffold-crud **/

var events = require('express').Router(),
    Model = require('../models/model-events.js');

    events.get('/', function(req, res) {
        Model.find(function(err, events){
        if (req.accepts('html', 'json') === 'json') {
            if(err) {
                return res.json(500, {
                    message: 'Error getting events.'
                });
            }
            return res.json(events);
        } else {
            if(err) {
                return res.send('500: Internal Server Error', 500);
            }
        return res.render('events/index', {events: events});
        }
    });
});

events.post('/', function(req, res) {
    var event = new Model({
        'title': req.body['title'],
        'start': req.body['start'],
        'end': req.body['end']
    });
    event.save(function(err, event){
        if (req.accepts('html', 'json') === 'json') {
            if(err) {
                return res.json(500, {
                    message: 'Error saving item.',
                    error: err
                });
            }
            return res.json({
                message: 'saved',
                _id: event._id
            });
        } else {
            if(err) {
                return res.send('500: Internal Server Error', 500);
            }
            return res.render('events/edit', {event: event});
        }
    });
});

events.get('/:id', function(req, res) {
    var id = req.params.id;
    Model.findOne({_id: id}, function(err, event){
        if (req.accepts('html', 'json') === 'json') {
            if(err) {
                return res.json(500, {
                    message: 'Error getting event.'
                });
            }
            if(!event) {
                return res.json(404, {
                    message: 'No such event.'
                });
            }
            return res.json(event);
        } else {
            if(err) {
                return res.send('500: Internal Server Error', 500);
            }
            if(!event) {
                return res.end('No such event');
            }
            return res.render('events/edit', {event: event, flash: 'Created.'});
        }
    });
});

events.put('/:id', function(req, res) {
    var id = req.params.id;
    Model.findOne({_id: id}, function(err, event){
        if (req.accepts('html', 'json') === 'json') {
            if(err) {
                return res.json(500, {
                    message: 'Error saving event',
                    error: err
                });
            }
            if(!event) {
                return res.json(404, {
                    message: 'No such event'
                });
            }
            event['name'] = req.body['name'] ? req.body['name'] : event['name'];
            event['start'] = req.body['start'] ? req.body['start'] : event['start'];
            event['end'] = req.body['end'] ? req.body['end'] : event['end'];
            event.save(function(err, event){
                if(err) {
                    return res.json(500, {
                        message: 'Error getting event.'
                    });
                }
                if(!event) {
                    return res.json(404, {
                        message: 'No such event'
                    });
                }
                return res.json(event);
            });
        } else {
            if(err) {
                return res.send('500: Internal Server Error', 500);
            }
            if(!event) {
                return res.end('No such event');
            }
            event['name'] = req.body['name'] ? req.body['name'] : event['name'];
            event['start'] = req.body['start'] ? req.body['start'] : event['start'];
            event['end'] = req.body['end'] ? req.body['end'] : event['end'];
            event.save(function(err, event){
                if(err) {
                    return res.send('500: Internal Server Error', 500);
                }
                if(!event) {
                    return res.end('No such event');
                }
                return res.render('events/edit', {event: event, flash: 'Saved.'});
            });
        }
    });
});

events.delete('/:id', function(req, res) {
    var id = req.params.id;
    Model.findOne({_id: id}, function(err, event){
        if (req.accepts('html', 'json') === 'json') {
            if(err) {
                return res.json(500, {
                    message: 'Error getting event.'
                });
            }
            if(!event) {
                return res.json(404, {
                    message: 'No such event'
                });
            }
            return res.json(event);
        } else {
            if(err) {
                return res.send('500: Internal Server Error', 500);
            }
            if(!event) {
                return res.end('No such event');
            }
            return res.render('events/index', {flash: 'Item deleted.'});
        }
    });
});

module.exports = events;