'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

/**
 * event model file
 * autogenerated by mongoose-scaffold-crud
 */

var eventsSchema = new Schema({
    name: 'String',
    start: 'Date',
    end: 'Date'
});

module.exports = mongoose.model('events', eventsSchema);

