'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;
    const options = {
        autoIndex: false, // Don't build indexes
        reconnectTries: Number.MAX_VALUE, // Never stop trying to reconnect
        reconnectInterval: 500, // Reconnect every 500ms
        poolSize: 10, // Maintain up to 10 socket connections
        // If not connected, return errors immediately rather than waiting for reconnect
        bufferMaxEntries: 0
      };
      mongoose.connect('mongodb://127.0.0.1:27017/local', options).then(
        () => { /** ready to use. The `mongoose.connect()` promise resolves to undefined. */ },
        err => { /** handle initial connection error */ }
      );
/**
 * user model file
 * autogenerated by mongoose-scaffold-crud
 */

var usersSchema = new Schema({
    name: 'String',
    userName: 'String',
    age: 'Number'
});

module.exports = mongoose.model('users', usersSchema);