'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

/**
 * event model file
 * autogenerated by mongoose-scaffold-crud
 */

var eventsSchema = new Schema({
    title: 'String',
    startDate: 'Date',
    endDate: 'Date',
    frequency: 'Number',
    days:[Number],
    startTime: 'String',
    endTime: 'String'
});

module.exports = mongoose.model('events', eventsSchema);

